### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by theoneandonly-vector** [LukasK13/ldap-mailcow#1]
When I run:
docker-compose up ldap-mailcow
I get:
```
mailcowcustomized_ldap-mailcow | 17.02.21 20:29:10 Checked user test.test@domain.tld, unchanged
mailcowcustomized_ldap-mailcow | 17.02.21 20:29:10 Checked user phone@domain.tld, unchanged
mailcowcustomized_ldap-mailcow | 17.02.21 20:29:10 Checked user user.name@domain.tld, unchanged
mailcowcustomized_ldap-mailcow | Traceback (most recent call last):
mailcowcustomized_ldap-mailcow |   File "//syncer.py", line 186, in <module>
mailcowcustomized_ldap-mailcow |     main()
mailcowcustomized_ldap-mailcow |   File "//syncer.py", line 32, in main
mailcowcustomized_ldap-mailcow |     sync()
mailcowcustomized_ldap-mailcow |   File "//syncer.py", line 57, in sync
mailcowcustomized_ldap-mailcow |     for (ldap_email, ldap_name, ldap_active) in ldap_results:
mailcowcustomized_ldap-mailcow |   File "//syncer.py", line 50, in <lambda>
mailcowcustomized_ldap-mailcow |     [i.decode() for i in x[1][config['LDAP_FIELDS_MAIL']]],
mailcowcustomized_ldap-mailcow | TypeError: list indices must be integers or slices, not str
mailcowcustomized_ldap-mailcow exited with code 1
```

my Settings docker-compose.override.yml:
```
version: '2.1'
services:

 ldap-mailcow:
    image: ac7ae338481b
    network_mode: host
    container_name: mailcowcustomized_ldap-mailcow
    depends_on:
        - nginx-mailcow
    volumes:
        - ./data/ldap:/db:rw
        - ./data/conf/dovecot:/conf/dovecot:rw
        - ./data/conf/sogo:/conf/sogo:rw
    environment:
        - LDAP-MAILCOW_LDAP_HOST=ldaps://portal.domain.tld
        - LDAP-MAILCOW_LDAP_BASE_DN=DC=domain,DC=tld
        - LDAP-MAILCOW_LDAP_BIND_DN=CN=sogosynchuser,CN=Users,DC=domain,DC=tld
        - LDAP-MAILCOW_LDAP_BIND_DN_PASSWORD=*********************************
        - LDAP-MAILCOW_API_HOST=https://mail.domain.tld
        - LDAP-MAILCOW_API_KEY=08B78A-51EB6C-F1C6D4-E23847-6D1ED5
        - LDAP-MAILCOW_API_SSL_VERIFY=1
        - LDAP-MAILCOW_LDAP_FILTER=(&(objectClass=user)(mail=*))
        - LDAP-MAILCOW_LDAP_FIELDS_MAIL=mail
        - LDAP-MAILCOW_LDAP_FIELDS_NAME=cn
        - LDAP-MAILCOW_SYNC_INTERVAL=30
        - LDAP-MAILCOW_EMAIL_DOMAINS=domain.tld
    extra_hosts:
        - "portal.domain.tld:10.255.255.1"
        - "mail.domain.tld:127.0.0.1"

 sogo-mailcow:
 #   image: mailcow/sogo:1.95
    extra_hosts:
        - "portal.domain.tld:10.255.255.1"

 dovecot-mailcow:
    extra_hosts:
        - "portal.domain.tld:10.255.255.1"

 postfix-mailcow:
    extra_hosts:
        - "portal.domain.tld:10.255.255.1"
 ```
